#!/bin/bash

helpFunction() {
  echo ""
  echo "Usage: $0 -p path to configuration path with .nii extension -e conda environment name"
  exit 1
}

while getopts p:e: opt; do
  case "${opt}" in
  p) CONFIG_PATH=${OPTARG} ;;
  e) CONDA_ENV=${OPTARG} ;;
  ?) helpFunction ;;
  esac
done

if [ -z "$CONFIG_PATH" ] ; then
  echo "Path to configuration file is missing. Using configuration file in the current working directory."
  CONFIG_PATH="$(pwd)/config.ini"
  echo "$CONFIG_PATH"
fi

EXEC_FILE="$(pwd)/make_predictions.py"
if [ -f "$EXEC_FILE" ] && [ -f "$CONFIG_PATH" ]; then
    conda activate "$CONDA_ENV"
    python "$EXEC_FILE" --config_path "$CONFIG_PATH"
    conda deactivate
fi
